apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: workloads
  annotations:
    example-only: "true"
spec:
  provider:
    gcpsm:
      projectID: replace-with-gcp-project
      auth:
        workloadIdentity:
          clusterLocation: replace-with-cluster-location
          clusterName: replace-with-cluster-name
          serviceAccountRef:
            name: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
  namespace: workloads
  annotations:
    example-only: "true"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: multicloud-workloads-redis-password
