apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: workloads
spec:
  tls:
    - hosts:
        - frontend.staging.example.com
      secretName: frontend-tls
  rules:
    - host: frontend.staging.example.com
