apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workloads
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
          env:
            - name: LOG_LEVEL
              value: info
