apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
spec:
  validationFailureAction: enforce
  rules:
  - name: check-pod-resource-limits
    match:
      resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
    exclude:
      resources:
        namespaces:
        - argocd
        - cert-manager
        - ingress-nginx
        - kube-node-lease
        - kube-public
        - kube-system
        - kyverno
        - observability
    validate:
      message: "All containers must set both requests and limits for cpu and memory."
      anyPattern:
      - spec:
          containers:
          - resources:
              limits:
                cpu: "*"
                memory: "*"
              requests:
                cpu: "*"
                memory: "*"
      - spec:
          template:
            spec:
              containers:
              - resources:
                  limits:
                    cpu: "*"
                    memory: "*"
                  requests:
                    cpu: "*"
                    memory: "*"
