apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-gcp-apps
  namespace: ${argocd_namespace}
  labels:
    app.kubernetes.io/part-of: platform
spec:
  generators:
  - list:
      elements:
      - appName: frontend
        appPath: gitops/apps/frontend/overlays/dev
      - appName: backend
        appPath: gitops/apps/backend/overlays/dev
      - appName: redis
        appPath: gitops/apps/redis/overlays/dev
  template:
    metadata:
      name: '{{appName}}-dev-gcp'
      labels:
        app.kubernetes.io/part-of: platform
    spec:
      project: default
      source:
        repoURL: ${git_repo_url}
        targetRevision: ${git_target_revision}
        path: '{{appPath}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: workloads
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
