apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: workloads
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 300m
              memory: 384Mi
          env:
            - name: LOG_LEVEL
              value: debug
